
export const metadata = {
  title: 'Negosud',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className="antialiased min-h-screen">
      {children}
      </body>
    </html>
  )
}
